name: Java CI with JaCoCo and SpotBugs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests with JaCoCo
        run: mvn clean verify jacoco:report

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

      - name: Run SpotBugs analysis
        run: mvn spotbugs:spotbugs

      - name: Upload SpotBugs XML report
        uses: lcollins/spotbugs-github-action@v3.1.0
        with:
          path: '**/target/spotbugsXml.xml'

      - name: Upload SpotBugs HTML report
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-report
          path: target/site/spotbugs.html
      - name: Run Jacoco and Upload Coverage Report
        uses: madrapps/jacoco-report@v1.7.1
        with:
          coverage-files: '**/target/site/jacoco/jacoco.xml'
          minimum-coverage: 0
